# Generated by Django 3.0.5 on 2020-05-22 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collaborators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, null=True)),
                ('description', models.CharField(max_length=120, null=True)),
                ('direction', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('category', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=60, null=True)),
            ],
            options={
                'verbose_name': 'Project Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('status', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=60, null=True)),
            ],
            options={
                'verbose_name': 'Project Status',
                'verbose_name_plural': 'Statuses',
            },
        ),
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('category', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=60, null=True)),
            ],
            options={
                'verbose_name': 'Task Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
                ('due', models.DateTimeField()),
                ('description', models.CharField(max_length=60, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.TaskCategory')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collaborators.Collaborator')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectCategory'),
        ),
        migrations.AddField(
            model_name='project',
            name='collaborators',
            field=models.ManyToManyField(blank=True, to='collaborators.Collaborator'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectStatus'),
        ),
    ]
