# Generated by Django 3.0.6 on 2020-06-02 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectbeneficiary',
            old_name='beneficiary',
            new_name='beneficiary_id',
        ),
        migrations.RenameField(
            model_name='projectbeneficiary',
            old_name='project',
            new_name='project_id',
        ),
    ]
