# Generated by Django 3.0.5 on 2020-05-19 06:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200519_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(default=datetime.datetime(2020, 5, 19, 6, 22, 22, 485402, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectCategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.ForeignKey(default=datetime.datetime(2020, 5, 19, 6, 22, 32, 885761, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectStatus'),
            preserve_default=False,
        ),
    ]
