# Generated by Django 3.0.6 on 2020-05-31 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0001_initial'),
        ('beneficiaries', '0001_initial'),
        ('projects', '0004_auto_20200526_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='beneficiaries',
            field=models.ManyToManyField(blank=True, related_name='projects', to='beneficiaries.Beneficiary'),
        ),
        migrations.AlterField(
            model_name='project',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='projects', to='collaborators.Collaborator'),
        ),
    ]
