# Generated by Django 3.0.5 on 2020-04-26 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Femenine')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
