# Generated by Django 3.0.6 on 2020-05-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
