# Generated by Django 3.0.5 on 2020-05-13 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborator',
            name='projects',
        ),
    ]
