# Generated by Django 3.0.5 on 2020-04-26 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaborator',
            old_name='edad',
            new_name='age',
        ),
    ]
