<template>
  <div>
    <h1>Landing Page</h1>
    Lorem ipsum dolor sit amet consectetur adipiscing elit, volutpat commodo viverra enim vel sapien sociosqu, molestie luctus laoreet egestas dictumst augue. Nisl sed ultrices suscipit nec tempus torquent natoque magnis enim porta luctus, commodo sem fringilla litora sociosqu hendrerit libero laoreet lectus mollis. Dictum imperdiet fusce dapibus odio mollis vel lectus id ut convallis dui, vehicula sodales libero tellus venenatis egestas aptent dictumst viverra eu sapien, habitant tortor dignissim senectus tristique aenean ridiculus netus phasellus cum. Eleifend placerat est rutrum ut vel gravida tristique vivamus commodo, sodales vestibulum phasellus inceptos aliquam nisl parturient volutpat, congue nisi malesuada eros tortor ullamcorper lacus imperdiet.

Nisl venenatis at montes nulla nascetur risus tellus dictum pulvinar, rutrum justo rhoncus natoque tristique neque ligula mauris senectus, posuere laoreet auctor quisque congue placerat gravida fusce. Congue etiam sociosqu bibendum ultrices pretium class egestas mollis curae aenean habitasse nibh, mus faucibus vivamus interdum hendrerit malesuada facilisis ad fringilla non facilisi dis, curabitur parturient diam posuere neque eros aliquam tincidunt porta iaculis dictumst. Habitasse elementum nibh ornare ligula primis mattis eleifend, quisque curabitur scelerisque sapien molestie mollis eget, semper iaculis eu aenean suspendisse dapibus.

Nam viverra eros phasellus conubia himenaeos lacus arcu ridiculus cubilia convallis et neque euismod aenean felis ac nec, facilisi nunc sagittis platea habitasse rhoncus posuere torquent lobortis metus vitae blandit mus est ut vel. Aliquet placerat conubia habitant ligula bibendum at malesuada metus vulputate magna interdum purus porttitor, pretium per nam nunc lectus tellus id nibh sagittis venenatis tortor. Metus lobortis tellus in massa hendrerit vivamus rutrum inceptos scelerisque eleifend, natoque nascetur molestie maecenas cursus quis lacus eu luctus, odio vitae nunc congue sociosqu euismod suspendisse aliquet curabitur. Mus interdum quis enim ridiculus nulla blandit, pharetra orci neque vehicula sociosqu tincidunt, dignissim leo auctor habitasse mollis, lacinia sociis nec tristique torquent.

Phasellus habitant ad potenti aptent maecenas inceptos aliquam facilisis suscipit accumsan justo urna, malesuada augue sodales donec fusce cum faucibus magna venenatis quisque molestie habitasse, feugiat tristique cursus nibh per vestibulum conubia pellentesque sociosqu tortor aliquet. Placerat aliquam nulla sodales auctor ultrices magnis egestas vel, sociosqu urna quis aenean nec augue magna, malesuada sem faucibus vivamus hac cursus fames. Nam habitant scelerisque enim erat ante maecenas non sollicitudin, gravida vestibulum urna nascetur arcu cursus cras conubia, malesuada leo luctus ultrices fermentum porta orci. Blandit nulla mattis vel lacinia potenti ultricies dictumst consequat id dictum, curabitur ad fermentum felis varius porta iaculis ac.

Nam lacinia interdum nulla lacus pharetra egestas natoque, odio mattis non aptent lectus eget rutrum, aliquam facilisis maecenas integer molestie litora. Magna phasellus sagittis class penatibus aliquet purus integer potenti, per interdum eget aliquam cubilia ligula risus massa, sollicitudin et netus hac laoreet nec nam. Penatibus facilisi suspendisse habitant bibendum nec orci lectus pretium placerat aptent, accumsan a integer porttitor cubilia auctor tellus euismod montes suscipit sed, turpis aliquam viverra consequat magnis vel sapien dis mus.

Suspendisse metus facilisis morbi aliquam risus purus cursus, eleifend nec tincidunt magnis aliquet condimentum, venenatis sodales pharetra rhoncus taciti egestas. Non maecenas suscipit montes nibh eget ligula posuere nec aliquam tempor, nostra senectus fusce cras torquent ridiculus turpis facilisi ut. Placerat lacinia dapibus nullam bibendum curae blandit vitae risus donec vivamus luctus, dis litora in sem magnis porttitor aenean euismod vulputate odio laoreet, facilisi metus natoque sodales taciti cum velit sapien inceptos enim. Tempor fusce per phasellus tellus faucibus nulla aptent iaculis tincidunt aenean, massa nibh nascetur dis commodo mauris vivamus fringilla cum, senectus tristique montes varius tempus accumsan lobortis platea sapien.

Class interdum non scelerisque sociosqu gravida pharetra varius erat, mauris bibendum sem fermentum porttitor felis cum sagittis, in vitae dis sed odio eros aliquet. Cras volutpat viverra vivamus dapibus habitant, nam porta potenti risus faucibus euismod, integer aenean purus non. Sociosqu aenean hac morbi pretium suspendisse dictumst lobortis arcu, elementum praesent proin gravida nostra fames leo natoque vehicula, ut posuere eros porttitor pellentesque facilisis tortor.
    <carousel />
    Lorem ipsum dolor sit amet consectetur adipiscing elit, volutpat commodo viverra enim vel sapien sociosqu, molestie luctus laoreet egestas dictumst augue. Nisl sed ultrices suscipit nec tempus torquent natoque magnis enim porta luctus, commodo sem fringilla litora sociosqu hendrerit libero laoreet lectus mollis. Dictum imperdiet fusce dapibus odio mollis vel lectus id ut convallis dui, vehicula sodales libero tellus venenatis egestas aptent dictumst viverra eu sapien, habitant tortor dignissim senectus tristique aenean ridiculus netus phasellus cum. Eleifend placerat est rutrum ut vel gravida tristique vivamus commodo, sodales vestibulum phasellus inceptos aliquam nisl parturient volutpat, congue nisi malesuada eros tortor ullamcorper lacus imperdiet.

Nisl venenatis at montes nulla nascetur risus tellus dictum pulvinar, rutrum justo rhoncus natoque tristique neque ligula mauris senectus, posuere laoreet auctor quisque congue placerat gravida fusce. Congue etiam sociosqu bibendum ultrices pretium class egestas mollis curae aenean habitasse nibh, mus faucibus vivamus interdum hendrerit malesuada facilisis ad fringilla non facilisi dis, curabitur parturient diam posuere neque eros aliquam tincidunt porta iaculis dictumst. Habitasse elementum nibh ornare ligula primis mattis eleifend, quisque curabitur scelerisque sapien molestie mollis eget, semper iaculis eu aenean suspendisse dapibus.

Nam viverra eros phasellus conubia himenaeos lacus arcu ridiculus cubilia convallis et neque euismod aenean felis ac nec, facilisi nunc sagittis platea habitasse rhoncus posuere torquent lobortis metus vitae blandit mus est ut vel. Aliquet placerat conubia habitant ligula bibendum at malesuada metus vulputate magna interdum purus porttitor, pretium per nam nunc lectus tellus id nibh sagittis venenatis tortor. Metus lobortis tellus in massa hendrerit vivamus rutrum inceptos scelerisque eleifend, natoque nascetur molestie maecenas cursus quis lacus eu luctus, odio vitae nunc congue sociosqu euismod suspendisse aliquet curabitur. Mus interdum quis enim ridiculus nulla blandit, pharetra orci neque vehicula sociosqu tincidunt, dignissim leo auctor habitasse mollis, lacinia sociis nec tristique torquent.

Phasellus habitant ad potenti aptent maecenas inceptos aliquam facilisis suscipit accumsan justo urna, malesuada augue sodales donec fusce cum faucibus magna venenatis quisque molestie habitasse, feugiat tristique cursus nibh per vestibulum conubia pellentesque sociosqu tortor aliquet. Placerat aliquam nulla sodales auctor ultrices magnis egestas vel, sociosqu urna quis aenean nec augue magna, malesuada sem faucibus vivamus hac cursus fames. Nam habitant scelerisque enim erat ante maecenas non sollicitudin, gravida vestibulum urna nascetur arcu cursus cras conubia, malesuada leo luctus ultrices fermentum porta orci. Blandit nulla mattis vel lacinia potenti ultricies dictumst consequat id dictum, curabitur ad fermentum felis varius porta iaculis ac.

Nam lacinia interdum nulla lacus pharetra egestas natoque, odio mattis non aptent lectus eget rutrum, aliquam facilisis maecenas integer molestie litora. Magna phasellus sagittis class penatibus aliquet purus integer potenti, per interdum eget aliquam cubilia ligula risus massa, sollicitudin et netus hac laoreet nec nam. Penatibus facilisi suspendisse habitant bibendum nec orci lectus pretium placerat aptent, accumsan a integer porttitor cubilia auctor tellus euismod montes suscipit sed, turpis aliquam viverra consequat magnis vel sapien dis mus.

Suspendisse metus facilisis morbi aliquam risus purus cursus, eleifend nec tincidunt magnis aliquet condimentum, venenatis sodales pharetra rhoncus taciti egestas. Non maecenas suscipit montes nibh eget ligula posuere nec aliquam tempor, nostra senectus fusce cras torquent ridiculus turpis facilisi ut. Placerat lacinia dapibus nullam bibendum curae blandit vitae risus donec vivamus luctus, dis litora in sem magnis porttitor aenean euismod vulputate odio laoreet, facilisi metus natoque sodales taciti cum velit sapien inceptos enim. Tempor fusce per phasellus tellus faucibus nulla aptent iaculis tincidunt aenean, massa nibh nascetur dis commodo mauris vivamus fringilla cum, senectus tristique montes varius tempus accumsan lobortis platea sapien.

Class interdum non scelerisque sociosqu gravida pharetra varius erat, mauris bibendum sem fermentum porttitor felis cum sagittis, in vitae dis sed odio eros aliquet. Cras volutpat viverra vivamus dapibus habitant, nam porta potenti risus faucibus euismod, integer aenean purus non. Sociosqu aenean hac morbi pretium suspendisse dictumst lobortis arcu, elementum praesent proin gravida nostra fames leo natoque vehicula, ut posuere eros porttitor pellentesque facilisis tortor.
  </div>
</template>

<script>
import carousel from "@/components/carousel";

export default {
  name: "landing",
  components: {
    carousel
  }
};
</script>

<style></style>